--------------------------------------------------------
--  File created - вторник-мая-26-2020   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table DAY_TYPES
--------------------------------------------------------

  CREATE TABLE "C##ANNA"."DAY_TYPES" 
   (	"ID" NUMBER(*,0) GENERATED BY DEFAULT ON NULL AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"TITLE" NVARCHAR2(64)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table DEPARTMENTS
--------------------------------------------------------

  CREATE TABLE "C##ANNA"."DEPARTMENTS" 
   (	"ID" NUMBER(*,0) GENERATED BY DEFAULT ON NULL AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"NAME" VARCHAR2(250 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table EMPLOYEES
--------------------------------------------------------

  CREATE TABLE "C##ANNA"."EMPLOYEES" 
   (	"ID" NUMBER(*,0) GENERATED BY DEFAULT ON NULL AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"NAME" VARCHAR2(50 BYTE), 
	"SURNAME" VARCHAR2(50 BYTE), 
	"DATE_OF_BIRTHDAY" DATE, 
	"ID_DEPARTMENT" NUMBER, 
	"POSITION" VARCHAR2(100 BYTE), 
	"ADDRESS" VARCHAR2(100 BYTE), 
	"REMOTE_WORK" NUMBER(1,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table EMPLOYEES_AND_CALENDAR_DAYS
--------------------------------------------------------

  CREATE TABLE "C##ANNA"."EMPLOYEES_AND_CALENDAR_DAYS" 
   (	"EMPLOYEE_ID" NUMBER(*,0), 
	"MARK_ID" NUMBER(*,0), 
	"WORK_CALENDAR_ID" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table MARKS
--------------------------------------------------------

  CREATE TABLE "C##ANNA"."MARKS" 
   (	"ID" NUMBER(*,0) GENERATED BY DEFAULT ON NULL AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"TITLE" NVARCHAR2(2), 
	"TRANSCRIPTION" NVARCHAR2(200)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table ROLES
--------------------------------------------------------

  CREATE TABLE "C##ANNA"."ROLES" 
   (	"ID" NUMBER(*,0) GENERATED BY DEFAULT ON NULL AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"NAME" VARCHAR2(250 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table USERS
--------------------------------------------------------

  CREATE TABLE "C##ANNA"."USERS" 
   (	"ID" NUMBER(*,0) GENERATED BY DEFAULT ON NULL AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"LOGIN" VARCHAR2(250 BYTE), 
	"PASSWORD" VARCHAR2(250 BYTE), 
	"ID_ROLE" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table WORK_CALENDAR
--------------------------------------------------------

  CREATE TABLE "C##ANNA"."WORK_CALENDAR" 
   (	"ID" NUMBER(*,0) GENERATED BY DEFAULT ON NULL AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"DAY" DATE, 
	"ID_DAY_TYPE" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for View ALL_EMPLOYEES
--------------------------------------------------------

  CREATE OR REPLACE FORCE EDITIONABLE VIEW "C##ANNA"."ALL_EMPLOYEES" ("ID", "NAME", "SURNAME", "DATE_OF_BIRTHDAY", "ID_DEPARTMENT", "depname", "POSITION", "ADDRESS", "REMOTE_WORK") AS 
  select 
        employees.id, employees.name, employees.surname, employees.date_of_birthday, employees.id_department,
        departments.name "depname", employees.position, employees.address, employees.remote_work
    from employees
    inner join departments on employees.id_department = departments.id
;
--------------------------------------------------------
--  DDL for View GET_MONTHS
--------------------------------------------------------

  CREATE OR REPLACE FORCE EDITIONABLE VIEW "C##ANNA"."GET_MONTHS" ("RES") AS 
  select to_char(mon, 'Month YYYY') as res
    from (
        SELECT distinct(TRUNC(TO_DATE(day), 'MONTH')) as mon FROM work_calendar
    ) order by mon
;
REM INSERTING into C##ANNA.DAY_TYPES
SET DEFINE OFF;
Insert into C##ANNA.DAY_TYPES (ID,TITLE) values ('1','выходной');
Insert into C##ANNA.DAY_TYPES (ID,TITLE) values ('2','рабочий');
Insert into C##ANNA.DAY_TYPES (ID,TITLE) values ('3','праздничный');
Insert into C##ANNA.DAY_TYPES (ID,TITLE) values ('4','предпраздничный');
REM INSERTING into C##ANNA.DEPARTMENTS
SET DEFINE OFF;
Insert into C##ANNA.DEPARTMENTS (ID,NAME) values ('2','Разработка');
Insert into C##ANNA.DEPARTMENTS (ID,NAME) values ('3','HR');
Insert into C##ANNA.DEPARTMENTS (ID,NAME) values ('21','Автоматизация тестирования');
REM INSERTING into C##ANNA.EMPLOYEES
SET DEFINE OFF;
Insert into C##ANNA.EMPLOYEES (ID,NAME,SURNAME,DATE_OF_BIRTHDAY,ID_DEPARTMENT,POSITION,ADDRESS,REMOTE_WORK) values ('61','Иван','Иванов',to_date('12.02.00','DD.MM.RR'),'2','Разработчик','СПБ, Невский пр.3/6  кв.1','1');
Insert into C##ANNA.EMPLOYEES (ID,NAME,SURNAME,DATE_OF_BIRTHDAY,ID_DEPARTMENT,POSITION,ADDRESS,REMOTE_WORK) values ('63','Петя','Петров',to_date('14.04.99','DD.MM.RR'),'3','Главный HR','СПБ, ул. Политехническая,д.13,кв.7','1');
Insert into C##ANNA.EMPLOYEES (ID,NAME,SURNAME,DATE_OF_BIRTHDAY,ID_DEPARTMENT,POSITION,ADDRESS,REMOTE_WORK) values ('103','Вася','Лебедев',to_date('12.01.89','DD.MM.RR'),'21','Глава отдела','СПБ','0');
REM INSERTING into C##ANNA.EMPLOYEES_AND_CALENDAR_DAYS
SET DEFINE OFF;
Insert into C##ANNA.EMPLOYEES_AND_CALENDAR_DAYS (EMPLOYEE_ID,MARK_ID,WORK_CALENDAR_ID) values ('63','1','688');
Insert into C##ANNA.EMPLOYEES_AND_CALENDAR_DAYS (EMPLOYEE_ID,MARK_ID,WORK_CALENDAR_ID) values ('63','1','650');
Insert into C##ANNA.EMPLOYEES_AND_CALENDAR_DAYS (EMPLOYEE_ID,MARK_ID,WORK_CALENDAR_ID) values ('61','5','509');
Insert into C##ANNA.EMPLOYEES_AND_CALENDAR_DAYS (EMPLOYEE_ID,MARK_ID,WORK_CALENDAR_ID) values ('61','8','510');
Insert into C##ANNA.EMPLOYEES_AND_CALENDAR_DAYS (EMPLOYEE_ID,MARK_ID,WORK_CALENDAR_ID) values ('61','1','511');
Insert into C##ANNA.EMPLOYEES_AND_CALENDAR_DAYS (EMPLOYEE_ID,MARK_ID,WORK_CALENDAR_ID) values ('61','1','512');
Insert into C##ANNA.EMPLOYEES_AND_CALENDAR_DAYS (EMPLOYEE_ID,MARK_ID,WORK_CALENDAR_ID) values ('61','1','513');
Insert into C##ANNA.EMPLOYEES_AND_CALENDAR_DAYS (EMPLOYEE_ID,MARK_ID,WORK_CALENDAR_ID) values ('61','1','508');
REM INSERTING into C##ANNA.MARKS
SET DEFINE OFF;
Insert into C##ANNA.MARKS (ID,TITLE,TRANSCRIPTION) values ('1','Я','Полный рабочий день');
Insert into C##ANNA.MARKS (ID,TITLE,TRANSCRIPTION) values ('2','Н','Отсутствие на рабочее место по невыясненным причинам');
Insert into C##ANNA.MARKS (ID,TITLE,TRANSCRIPTION) values ('3','В','Выходные и праздничные дни');
Insert into C##ANNA.MARKS (ID,TITLE,TRANSCRIPTION) values ('5','Б','Дни временной нетрудоспособности');
Insert into C##ANNA.MARKS (ID,TITLE,TRANSCRIPTION) values ('7','ОТ',' Ежегодный основной оплаченный отпуск');
Insert into C##ANNA.MARKS (ID,TITLE,TRANSCRIPTION) values ('8','До','Неоплачиваемый отпуск (отпуск за свой счет)');
Insert into C##ANNA.MARKS (ID,TITLE,TRANSCRIPTION) values ('9','Хд','Хозяйственный день');
Insert into C##ANNA.MARKS (ID,TITLE,TRANSCRIPTION) values ('10','У','отпуск на период обучения');
Insert into C##ANNA.MARKS (ID,TITLE,TRANSCRIPTION) values ('11','Ож','Отпуск по уходу за ребенком');
Insert into C##ANNA.MARKS (ID,TITLE,TRANSCRIPTION) values ('21','Рв','Работа в праздничные и выходные дни; а также работа в праздничные и выходные дни, при
нахождении в командировке');
Insert into C##ANNA.MARKS (ID,TITLE,TRANSCRIPTION) values ('22','К','Командировочные дни; а также, выходные (нерабочие) дни при нахождении в командировке,
когда сотрудник отдыхает, в соответствии с графиком работы ООО «Наука»');
REM INSERTING into C##ANNA.ROLES
SET DEFINE OFF;
Insert into C##ANNA.ROLES (ID,NAME) values ('1','Табельщик');
Insert into C##ANNA.ROLES (ID,NAME) values ('2','Администратор справочника департаментов');
Insert into C##ANNA.ROLES (ID,NAME) values ('3','Администратор справочника работников');
REM INSERTING into C##ANNA.USERS
SET DEFINE OFF;
Insert into C##ANNA.USERS (ID,LOGIN,PASSWORD,ID_ROLE) values ('21','timekeeper','113AEC57634113E2D08509BEB19BA979520D4C32','1');
Insert into C##ANNA.USERS (ID,LOGIN,PASSWORD,ID_ROLE) values ('22','admin_departments','7DDF91A2D010F12082047BA2C0E18A7E3E10E2E8','2');
Insert into C##ANNA.USERS (ID,LOGIN,PASSWORD,ID_ROLE) values ('23','admin_employees','E7C93D8537C9CF6B889FF90C7A04A8A7E74E99AC','3');
REM INSERTING into C##ANNA.WORK_CALENDAR
SET DEFINE OFF;
Insert into C##ANNA.WORK_CALENDAR (ID,DAY,ID_DAY_TYPE) values ('508',to_date('01.01.20','DD.MM.RR'),'3');
Insert into C##ANNA.WORK_CALENDAR (ID,DAY,ID_DAY_TYPE) values ('509',to_date('02.01.20','DD.MM.RR'),'1');
Insert into C##ANNA.WORK_CALENDAR (ID,DAY,ID_DAY_TYPE) values ('510',to_date('03.01.20','DD.MM.RR'),'1');
Insert into C##ANNA.WORK_CALENDAR (ID,DAY,ID_DAY_TYPE) values ('511',to_date('04.01.20','DD.MM.RR'),'1');
Insert into C##ANNA.WORK_CALENDAR (ID,DAY,ID_DAY_TYPE) values ('512',to_date('05.01.20','DD.MM.RR'),'1');
Insert into C##ANNA.WORK_CALENDAR (ID,DAY,ID_DAY_TYPE) values ('513',to_date('06.01.20','DD.MM.RR'),'1');
Insert into C##ANNA.WORK_CALENDAR (ID,DAY,ID_DAY_TYPE) values ('514',to_date('07.01.20','DD.MM.RR'),'1');
Insert into C##ANNA.WORK_CALENDAR (ID,DAY,ID_DAY_TYPE) values ('515',to_date('08.01.20','DD.MM.RR'),'1');
Insert into C##ANNA.WORK_CALENDAR (ID,DAY,ID_DAY_TYPE) values ('516',to_date('09.01.20','DD.MM.RR'),'2');
Insert into C##ANNA.WORK_CALENDAR (ID,DAY,ID_DAY_TYPE) values ('517',to_date('10.01.20','DD.MM.RR'),'2');
Insert into C##ANNA.WORK_CALENDAR (ID,DAY,ID_DAY_TYPE) values ('518',to_date('11.01.20','DD.MM.RR'),'1');
Insert into C##ANNA.WORK_CALENDAR (ID,DAY,ID_DAY_TYPE) values ('519',to_date('12.01.20','DD.MM.RR'),'1');
Insert into C##ANNA.WORK_CALENDAR (ID,DAY,ID_DAY_TYPE) values ('520',to_date('13.01.20','DD.MM.RR'),'2');
Insert into C##ANNA.WORK_CALENDAR (ID,DAY,ID_DAY_TYPE) values ('521',to_date('14.01.20','DD.MM.RR'),'2');
Insert into C##ANNA.WORK_CALENDAR (ID,DAY,ID_DAY_TYPE) values ('522',to_date('15.01.20','DD.MM.RR'),'2');
Insert into C##ANNA.WORK_CALENDAR (ID,DAY,ID_DAY_TYPE) values ('523',to_date('16.01.20','DD.MM.RR'),'2');
Insert into C##ANNA.WORK_CALENDAR (ID,DAY,ID_DAY_TYPE) values ('524',to_date('17.01.20','DD.MM.RR'),'2');
Insert into C##ANNA.WORK_CALENDAR (ID,DAY,ID_DAY_TYPE) values ('525',to_date('18.01.20','DD.MM.RR'),'1');
Insert into C##ANNA.WORK_CALENDAR (ID,DAY,ID_DAY_TYPE) values ('526',to_date('19.01.20','DD.MM.RR'),'1');
Insert into C##ANNA.WORK_CALENDAR (ID,DAY,ID_DAY_TYPE) values ('527',to_date('20.01.20','DD.MM.RR'),'2');
Insert into C##ANNA.WORK_CALENDAR (ID,DAY,ID_DAY_TYPE) values ('528',to_date('21.01.20','DD.MM.RR'),'2');
Insert into C##ANNA.WORK_CALENDAR (ID,DAY,ID_DAY_TYPE) values ('529',to_date('22.01.20','DD.MM.RR'),'2');
Insert into C##ANNA.WORK_CALENDAR (ID,DAY,ID_DAY_TYPE) values ('530',to_date('23.01.20','DD.MM.RR'),'2');
Insert into C##ANNA.WORK_CALENDAR (ID,DAY,ID_DAY_TYPE) values ('531',to_date('24.01.20','DD.MM.RR'),'2');
Insert into C##ANNA.WORK_CALENDAR (ID,DAY,ID_DAY_TYPE) values ('532',to_date('25.01.20','DD.MM.RR'),'1');
Insert into C##ANNA.WORK_CALENDAR (ID,DAY,ID_DAY_TYPE) values ('533',to_date('26.01.20','DD.MM.RR'),'1');
Insert into C##ANNA.WORK_CALENDAR (ID,DAY,ID_DAY_TYPE) values ('534',to_date('27.01.20','DD.MM.RR'),'2');
Insert into C##ANNA.WORK_CALENDAR (ID,DAY,ID_DAY_TYPE) values ('535',to_date('28.01.20','DD.MM.RR'),'2');
Insert into C##ANNA.WORK_CALENDAR (ID,DAY,ID_DAY_TYPE) values ('536',to_date('29.01.20','DD.MM.RR'),'2');
Insert into C##ANNA.WORK_CALENDAR (ID,DAY,ID_DAY_TYPE) values ('537',to_date('30.01.20','DD.MM.RR'),'2');
Insert into C##ANNA.WORK_CALENDAR (ID,DAY,ID_DAY_TYPE) values ('538',to_date('31.01.20','DD.MM.RR'),'2');
Insert into C##ANNA.WORK_CALENDAR (ID,DAY,ID_DAY_TYPE) values ('539',to_date('01.02.20','DD.MM.RR'),'1');
Insert into C##ANNA.WORK_CALENDAR (ID,DAY,ID_DAY_TYPE) values ('540',to_date('02.02.20','DD.MM.RR'),'1');
Insert into C##ANNA.WORK_CALENDAR (ID,DAY,ID_DAY_TYPE) values ('541',to_date('03.02.20','DD.MM.RR'),'2');
Insert into C##ANNA.WORK_CALENDAR (ID,DAY,ID_DAY_TYPE) values ('542',to_date('04.02.20','DD.MM.RR'),'2');
Insert into C##ANNA.WORK_CALENDAR (ID,DAY,ID_DAY_TYPE) values ('543',to_date('05.02.20','DD.MM.RR'),'2');
Insert into C##ANNA.WORK_CALENDAR (ID,DAY,ID_DAY_TYPE) values ('544',to_date('06.02.20','DD.MM.RR'),'2');
Insert into C##ANNA.WORK_CALENDAR (ID,DAY,ID_DAY_TYPE) values ('545',to_date('07.02.20','DD.MM.RR'),'2');
Insert into C##ANNA.WORK_CALENDAR (ID,DAY,ID_DAY_TYPE) values ('546',to_date('08.02.20','DD.MM.RR'),'1');
Insert into C##ANNA.WORK_CALENDAR (ID,DAY,ID_DAY_TYPE) values ('547',to_date('09.02.20','DD.MM.RR'),'1');
Insert into C##ANNA.WORK_CALENDAR (ID,DAY,ID_DAY_TYPE) values ('548',to_date('10.02.20','DD.MM.RR'),'2');
Insert into C##ANNA.WORK_CALENDAR (ID,DAY,ID_DAY_TYPE) values ('549',to_date('11.02.20','DD.MM.RR'),'2');
Insert into C##ANNA.WORK_CALENDAR (ID,DAY,ID_DAY_TYPE) values ('550',to_date('12.02.20','DD.MM.RR'),'2');
Insert into C##ANNA.WORK_CALENDAR (ID,DAY,ID_DAY_TYPE) values ('551',to_date('13.02.20','DD.MM.RR'),'2');
Insert into C##ANNA.WORK_CALENDAR (ID,DAY,ID_DAY_TYPE) values ('552',to_date('14.02.20','DD.MM.RR'),'2');
Insert into C##ANNA.WORK_CALENDAR (ID,DAY,ID_DAY_TYPE) values ('553',to_date('15.02.20','DD.MM.RR'),'1');
Insert into C##ANNA.WORK_CALENDAR (ID,DAY,ID_DAY_TYPE) values ('554',to_date('16.02.20','DD.MM.RR'),'1');
Insert into C##ANNA.WORK_CALENDAR (ID,DAY,ID_DAY_TYPE) values ('555',to_date('17.02.20','DD.MM.RR'),'2');
Insert into C##ANNA.WORK_CALENDAR (ID,DAY,ID_DAY_TYPE) values ('556',to_date('18.02.20','DD.MM.RR'),'2');
Insert into C##ANNA.WORK_CALENDAR (ID,DAY,ID_DAY_TYPE) values ('557',to_date('19.02.20','DD.MM.RR'),'2');
Insert into C##ANNA.WORK_CALENDAR (ID,DAY,ID_DAY_TYPE) values ('558',to_date('20.02.20','DD.MM.RR'),'2');
Insert into C##ANNA.WORK_CALENDAR (ID,DAY,ID_DAY_TYPE) values ('559',to_date('21.02.20','DD.MM.RR'),'2');
Insert into C##ANNA.WORK_CALENDAR (ID,DAY,ID_DAY_TYPE) values ('560',to_date('22.02.20','DD.MM.RR'),'1');
Insert into C##ANNA.WORK_CALENDAR (ID,DAY,ID_DAY_TYPE) values ('561',to_date('23.02.20','DD.MM.RR'),'3');
Insert into C##ANNA.WORK_CALENDAR (ID,DAY,ID_DAY_TYPE) values ('562',to_date('24.02.20','DD.MM.RR'),'1');
Insert into C##ANNA.WORK_CALENDAR (ID,DAY,ID_DAY_TYPE) values ('563',to_date('25.02.20','DD.MM.RR'),'2');
Insert into C##ANNA.WORK_CALENDAR (ID,DAY,ID_DAY_TYPE) values ('564',to_date('26.02.20','DD.MM.RR'),'2');
Insert into C##ANNA.WORK_CALENDAR (ID,DAY,ID_DAY_TYPE) values ('565',to_date('27.02.20','DD.MM.RR'),'2');
Insert into C##ANNA.WORK_CALENDAR (ID,DAY,ID_DAY_TYPE) values ('566',to_date('28.02.20','DD.MM.RR'),'2');
Insert into C##ANNA.WORK_CALENDAR (ID,DAY,ID_DAY_TYPE) values ('567',to_date('29.02.20','DD.MM.RR'),'1');
Insert into C##ANNA.WORK_CALENDAR (ID,DAY,ID_DAY_TYPE) values ('568',to_date('01.03.20','DD.MM.RR'),'1');
Insert into C##ANNA.WORK_CALENDAR (ID,DAY,ID_DAY_TYPE) values ('569',to_date('02.03.20','DD.MM.RR'),'2');
Insert into C##ANNA.WORK_CALENDAR (ID,DAY,ID_DAY_TYPE) values ('570',to_date('03.03.20','DD.MM.RR'),'2');
Insert into C##ANNA.WORK_CALENDAR (ID,DAY,ID_DAY_TYPE) values ('571',to_date('04.03.20','DD.MM.RR'),'2');
Insert into C##ANNA.WORK_CALENDAR (ID,DAY,ID_DAY_TYPE) values ('572',to_date('05.03.20','DD.MM.RR'),'2');
Insert into C##ANNA.WORK_CALENDAR (ID,DAY,ID_DAY_TYPE) values ('573',to_date('06.03.20','DD.MM.RR'),'2');
Insert into C##ANNA.WORK_CALENDAR (ID,DAY,ID_DAY_TYPE) values ('574',to_date('07.03.20','DD.MM.RR'),'1');
Insert into C##ANNA.WORK_CALENDAR (ID,DAY,ID_DAY_TYPE) values ('575',to_date('08.03.20','DD.MM.RR'),'3');
Insert into C##ANNA.WORK_CALENDAR (ID,DAY,ID_DAY_TYPE) values ('576',to_date('09.03.20','DD.MM.RR'),'1');
Insert into C##ANNA.WORK_CALENDAR (ID,DAY,ID_DAY_TYPE) values ('577',to_date('10.03.20','DD.MM.RR'),'2');
Insert into C##ANNA.WORK_CALENDAR (ID,DAY,ID_DAY_TYPE) values ('578',to_date('11.03.20','DD.MM.RR'),'2');
Insert into C##ANNA.WORK_CALENDAR (ID,DAY,ID_DAY_TYPE) values ('579',to_date('12.03.20','DD.MM.RR'),'2');
Insert into C##ANNA.WORK_CALENDAR (ID,DAY,ID_DAY_TYPE) values ('580',to_date('13.03.20','DD.MM.RR'),'2');
Insert into C##ANNA.WORK_CALENDAR (ID,DAY,ID_DAY_TYPE) values ('581',to_date('14.03.20','DD.MM.RR'),'1');
Insert into C##ANNA.WORK_CALENDAR (ID,DAY,ID_DAY_TYPE) values ('582',to_date('15.03.20','DD.MM.RR'),'1');
Insert into C##ANNA.WORK_CALENDAR (ID,DAY,ID_DAY_TYPE) values ('583',to_date('16.03.20','DD.MM.RR'),'2');
Insert into C##ANNA.WORK_CALENDAR (ID,DAY,ID_DAY_TYPE) values ('584',to_date('17.03.20','DD.MM.RR'),'2');
Insert into C##ANNA.WORK_CALENDAR (ID,DAY,ID_DAY_TYPE) values ('585',to_date('18.03.20','DD.MM.RR'),'2');
Insert into C##ANNA.WORK_CALENDAR (ID,DAY,ID_DAY_TYPE) values ('586',to_date('19.03.20','DD.MM.RR'),'2');
Insert into C##ANNA.WORK_CALENDAR (ID,DAY,ID_DAY_TYPE) values ('587',to_date('20.03.20','DD.MM.RR'),'2');
Insert into C##ANNA.WORK_CALENDAR (ID,DAY,ID_DAY_TYPE) values ('588',to_date('21.03.20','DD.MM.RR'),'1');
Insert into C##ANNA.WORK_CALENDAR (ID,DAY,ID_DAY_TYPE) values ('589',to_date('22.03.20','DD.MM.RR'),'1');
Insert into C##ANNA.WORK_CALENDAR (ID,DAY,ID_DAY_TYPE) values ('590',to_date('23.03.20','DD.MM.RR'),'2');
Insert into C##ANNA.WORK_CALENDAR (ID,DAY,ID_DAY_TYPE) values ('591',to_date('24.03.20','DD.MM.RR'),'2');
Insert into C##ANNA.WORK_CALENDAR (ID,DAY,ID_DAY_TYPE) values ('592',to_date('25.03.20','DD.MM.RR'),'2');
Insert into C##ANNA.WORK_CALENDAR (ID,DAY,ID_DAY_TYPE) values ('593',to_date('26.03.20','DD.MM.RR'),'2');
Insert into C##ANNA.WORK_CALENDAR (ID,DAY,ID_DAY_TYPE) values ('594',to_date('27.03.20','DD.MM.RR'),'2');
Insert into C##ANNA.WORK_CALENDAR (ID,DAY,ID_DAY_TYPE) values ('595',to_date('28.03.20','DD.MM.RR'),'1');
Insert into C##ANNA.WORK_CALENDAR (ID,DAY,ID_DAY_TYPE) values ('596',to_date('29.03.20','DD.MM.RR'),'1');
Insert into C##ANNA.WORK_CALENDAR (ID,DAY,ID_DAY_TYPE) values ('597',to_date('30.03.20','DD.MM.RR'),'2');
Insert into C##ANNA.WORK_CALENDAR (ID,DAY,ID_DAY_TYPE) values ('598',to_date('31.03.20','DD.MM.RR'),'2');
Insert into C##ANNA.WORK_CALENDAR (ID,DAY,ID_DAY_TYPE) values ('599',to_date('01.04.20','DD.MM.RR'),'2');
Insert into C##ANNA.WORK_CALENDAR (ID,DAY,ID_DAY_TYPE) values ('600',to_date('02.04.20','DD.MM.RR'),'2');
Insert into C##ANNA.WORK_CALENDAR (ID,DAY,ID_DAY_TYPE) values ('601',to_date('03.04.20','DD.MM.RR'),'2');
Insert into C##ANNA.WORK_CALENDAR (ID,DAY,ID_DAY_TYPE) values ('602',to_date('04.04.20','DD.MM.RR'),'1');
Insert into C##ANNA.WORK_CALENDAR (ID,DAY,ID_DAY_TYPE) values ('603',to_date('05.04.20','DD.MM.RR'),'1');
Insert into C##ANNA.WORK_CALENDAR (ID,DAY,ID_DAY_TYPE) values ('604',to_date('06.04.20','DD.MM.RR'),'2');
Insert into C##ANNA.WORK_CALENDAR (ID,DAY,ID_DAY_TYPE) values ('605',to_date('07.04.20','DD.MM.RR'),'2');
Insert into C##ANNA.WORK_CALENDAR (ID,DAY,ID_DAY_TYPE) values ('606',to_date('08.04.20','DD.MM.RR'),'2');
Insert into C##ANNA.WORK_CALENDAR (ID,DAY,ID_DAY_TYPE) values ('607',to_date('09.04.20','DD.MM.RR'),'2');
Insert into C##ANNA.WORK_CALENDAR (ID,DAY,ID_DAY_TYPE) values ('608',to_date('10.04.20','DD.MM.RR'),'2');
Insert into C##ANNA.WORK_CALENDAR (ID,DAY,ID_DAY_TYPE) values ('609',to_date('11.04.20','DD.MM.RR'),'1');
Insert into C##ANNA.WORK_CALENDAR (ID,DAY,ID_DAY_TYPE) values ('610',to_date('12.04.20','DD.MM.RR'),'1');
Insert into C##ANNA.WORK_CALENDAR (ID,DAY,ID_DAY_TYPE) values ('611',to_date('13.04.20','DD.MM.RR'),'2');
Insert into C##ANNA.WORK_CALENDAR (ID,DAY,ID_DAY_TYPE) values ('612',to_date('14.04.20','DD.MM.RR'),'2');
Insert into C##ANNA.WORK_CALENDAR (ID,DAY,ID_DAY_TYPE) values ('613',to_date('15.04.20','DD.MM.RR'),'2');
Insert into C##ANNA.WORK_CALENDAR (ID,DAY,ID_DAY_TYPE) values ('614',to_date('16.04.20','DD.MM.RR'),'2');
Insert into C##ANNA.WORK_CALENDAR (ID,DAY,ID_DAY_TYPE) values ('615',to_date('17.04.20','DD.MM.RR'),'2');
Insert into C##ANNA.WORK_CALENDAR (ID,DAY,ID_DAY_TYPE) values ('616',to_date('18.04.20','DD.MM.RR'),'1');
Insert into C##ANNA.WORK_CALENDAR (ID,DAY,ID_DAY_TYPE) values ('617',to_date('19.04.20','DD.MM.RR'),'1');
Insert into C##ANNA.WORK_CALENDAR (ID,DAY,ID_DAY_TYPE) values ('618',to_date('20.04.20','DD.MM.RR'),'2');
Insert into C##ANNA.WORK_CALENDAR (ID,DAY,ID_DAY_TYPE) values ('619',to_date('21.04.20','DD.MM.RR'),'2');
Insert into C##ANNA.WORK_CALENDAR (ID,DAY,ID_DAY_TYPE) values ('620',to_date('22.04.20','DD.MM.RR'),'2');
Insert into C##ANNA.WORK_CALENDAR (ID,DAY,ID_DAY_TYPE) values ('621',to_date('23.04.20','DD.MM.RR'),'2');
Insert into C##ANNA.WORK_CALENDAR (ID,DAY,ID_DAY_TYPE) values ('622',to_date('24.04.20','DD.MM.RR'),'2');
Insert into C##ANNA.WORK_CALENDAR (ID,DAY,ID_DAY_TYPE) values ('623',to_date('25.04.20','DD.MM.RR'),'1');
Insert into C##ANNA.WORK_CALENDAR (ID,DAY,ID_DAY_TYPE) values ('624',to_date('26.04.20','DD.MM.RR'),'1');
Insert into C##ANNA.WORK_CALENDAR (ID,DAY,ID_DAY_TYPE) values ('625',to_date('27.04.20','DD.MM.RR'),'2');
Insert into C##ANNA.WORK_CALENDAR (ID,DAY,ID_DAY_TYPE) values ('626',to_date('28.04.20','DD.MM.RR'),'2');
Insert into C##ANNA.WORK_CALENDAR (ID,DAY,ID_DAY_TYPE) values ('627',to_date('29.04.20','DD.MM.RR'),'2');
Insert into C##ANNA.WORK_CALENDAR (ID,DAY,ID_DAY_TYPE) values ('628',to_date('30.04.20','DD.MM.RR'),'2');
Insert into C##ANNA.WORK_CALENDAR (ID,DAY,ID_DAY_TYPE) values ('629',to_date('01.05.20','DD.MM.RR'),'3');
Insert into C##ANNA.WORK_CALENDAR (ID,DAY,ID_DAY_TYPE) values ('630',to_date('02.05.20','DD.MM.RR'),'1');
Insert into C##ANNA.WORK_CALENDAR (ID,DAY,ID_DAY_TYPE) values ('631',to_date('03.05.20','DD.MM.RR'),'1');
Insert into C##ANNA.WORK_CALENDAR (ID,DAY,ID_DAY_TYPE) values ('632',to_date('04.05.20','DD.MM.RR'),'1');
Insert into C##ANNA.WORK_CALENDAR (ID,DAY,ID_DAY_TYPE) values ('633',to_date('05.05.20','DD.MM.RR'),'1');
Insert into C##ANNA.WORK_CALENDAR (ID,DAY,ID_DAY_TYPE) values ('634',to_date('06.05.20','DD.MM.RR'),'2');
Insert into C##ANNA.WORK_CALENDAR (ID,DAY,ID_DAY_TYPE) values ('635',to_date('07.05.20','DD.MM.RR'),'2');
Insert into C##ANNA.WORK_CALENDAR (ID,DAY,ID_DAY_TYPE) values ('636',to_date('08.05.20','DD.MM.RR'),'4');
Insert into C##ANNA.WORK_CALENDAR (ID,DAY,ID_DAY_TYPE) values ('637',to_date('09.05.20','DD.MM.RR'),'3');
Insert into C##ANNA.WORK_CALENDAR (ID,DAY,ID_DAY_TYPE) values ('638',to_date('10.05.20','DD.MM.RR'),'1');
Insert into C##ANNA.WORK_CALENDAR (ID,DAY,ID_DAY_TYPE) values ('639',to_date('11.05.20','DD.MM.RR'),'1');
Insert into C##ANNA.WORK_CALENDAR (ID,DAY,ID_DAY_TYPE) values ('640',to_date('12.05.20','DD.MM.RR'),'2');
Insert into C##ANNA.WORK_CALENDAR (ID,DAY,ID_DAY_TYPE) values ('641',to_date('13.05.20','DD.MM.RR'),'2');
Insert into C##ANNA.WORK_CALENDAR (ID,DAY,ID_DAY_TYPE) values ('642',to_date('14.05.20','DD.MM.RR'),'2');
Insert into C##ANNA.WORK_CALENDAR (ID,DAY,ID_DAY_TYPE) values ('643',to_date('15.05.20','DD.MM.RR'),'2');
Insert into C##ANNA.WORK_CALENDAR (ID,DAY,ID_DAY_TYPE) values ('644',to_date('16.05.20','DD.MM.RR'),'1');
Insert into C##ANNA.WORK_CALENDAR (ID,DAY,ID_DAY_TYPE) values ('645',to_date('17.05.20','DD.MM.RR'),'1');
Insert into C##ANNA.WORK_CALENDAR (ID,DAY,ID_DAY_TYPE) values ('646',to_date('18.05.20','DD.MM.RR'),'2');
Insert into C##ANNA.WORK_CALENDAR (ID,DAY,ID_DAY_TYPE) values ('647',to_date('19.05.20','DD.MM.RR'),'2');
Insert into C##ANNA.WORK_CALENDAR (ID,DAY,ID_DAY_TYPE) values ('648',to_date('20.05.20','DD.MM.RR'),'2');
Insert into C##ANNA.WORK_CALENDAR (ID,DAY,ID_DAY_TYPE) values ('649',to_date('21.05.20','DD.MM.RR'),'2');
Insert into C##ANNA.WORK_CALENDAR (ID,DAY,ID_DAY_TYPE) values ('650',to_date('22.05.20','DD.MM.RR'),'2');
Insert into C##ANNA.WORK_CALENDAR (ID,DAY,ID_DAY_TYPE) values ('651',to_date('23.05.20','DD.MM.RR'),'1');
Insert into C##ANNA.WORK_CALENDAR (ID,DAY,ID_DAY_TYPE) values ('652',to_date('24.05.20','DD.MM.RR'),'1');
Insert into C##ANNA.WORK_CALENDAR (ID,DAY,ID_DAY_TYPE) values ('653',to_date('25.05.20','DD.MM.RR'),'2');
Insert into C##ANNA.WORK_CALENDAR (ID,DAY,ID_DAY_TYPE) values ('654',to_date('26.05.20','DD.MM.RR'),'2');
Insert into C##ANNA.WORK_CALENDAR (ID,DAY,ID_DAY_TYPE) values ('655',to_date('27.05.20','DD.MM.RR'),'2');
Insert into C##ANNA.WORK_CALENDAR (ID,DAY,ID_DAY_TYPE) values ('656',to_date('28.05.20','DD.MM.RR'),'2');
Insert into C##ANNA.WORK_CALENDAR (ID,DAY,ID_DAY_TYPE) values ('657',to_date('29.05.20','DD.MM.RR'),'2');
Insert into C##ANNA.WORK_CALENDAR (ID,DAY,ID_DAY_TYPE) values ('658',to_date('30.05.20','DD.MM.RR'),'1');
Insert into C##ANNA.WORK_CALENDAR (ID,DAY,ID_DAY_TYPE) values ('659',to_date('31.05.20','DD.MM.RR'),'1');
Insert into C##ANNA.WORK_CALENDAR (ID,DAY,ID_DAY_TYPE) values ('660',to_date('01.06.20','DD.MM.RR'),'2');
Insert into C##ANNA.WORK_CALENDAR (ID,DAY,ID_DAY_TYPE) values ('661',to_date('02.06.20','DD.MM.RR'),'2');
Insert into C##ANNA.WORK_CALENDAR (ID,DAY,ID_DAY_TYPE) values ('662',to_date('03.06.20','DD.MM.RR'),'2');
Insert into C##ANNA.WORK_CALENDAR (ID,DAY,ID_DAY_TYPE) values ('663',to_date('04.06.20','DD.MM.RR'),'2');
Insert into C##ANNA.WORK_CALENDAR (ID,DAY,ID_DAY_TYPE) values ('664',to_date('05.06.20','DD.MM.RR'),'2');
Insert into C##ANNA.WORK_CALENDAR (ID,DAY,ID_DAY_TYPE) values ('665',to_date('06.06.20','DD.MM.RR'),'1');
Insert into C##ANNA.WORK_CALENDAR (ID,DAY,ID_DAY_TYPE) values ('666',to_date('07.06.20','DD.MM.RR'),'1');
Insert into C##ANNA.WORK_CALENDAR (ID,DAY,ID_DAY_TYPE) values ('667',to_date('08.06.20','DD.MM.RR'),'2');
Insert into C##ANNA.WORK_CALENDAR (ID,DAY,ID_DAY_TYPE) values ('668',to_date('09.06.20','DD.MM.RR'),'2');
Insert into C##ANNA.WORK_CALENDAR (ID,DAY,ID_DAY_TYPE) values ('669',to_date('10.06.20','DD.MM.RR'),'2');
Insert into C##ANNA.WORK_CALENDAR (ID,DAY,ID_DAY_TYPE) values ('670',to_date('11.06.20','DD.MM.RR'),'2');
Insert into C##ANNA.WORK_CALENDAR (ID,DAY,ID_DAY_TYPE) values ('671',to_date('12.06.20','DD.MM.RR'),'2');
Insert into C##ANNA.WORK_CALENDAR (ID,DAY,ID_DAY_TYPE) values ('672',to_date('13.06.20','DD.MM.RR'),'1');
Insert into C##ANNA.WORK_CALENDAR (ID,DAY,ID_DAY_TYPE) values ('673',to_date('14.06.20','DD.MM.RR'),'1');
Insert into C##ANNA.WORK_CALENDAR (ID,DAY,ID_DAY_TYPE) values ('674',to_date('15.06.20','DD.MM.RR'),'2');
Insert into C##ANNA.WORK_CALENDAR (ID,DAY,ID_DAY_TYPE) values ('675',to_date('16.06.20','DD.MM.RR'),'2');
Insert into C##ANNA.WORK_CALENDAR (ID,DAY,ID_DAY_TYPE) values ('676',to_date('17.06.20','DD.MM.RR'),'2');
Insert into C##ANNA.WORK_CALENDAR (ID,DAY,ID_DAY_TYPE) values ('677',to_date('18.06.20','DD.MM.RR'),'2');
Insert into C##ANNA.WORK_CALENDAR (ID,DAY,ID_DAY_TYPE) values ('678',to_date('19.06.20','DD.MM.RR'),'2');
Insert into C##ANNA.WORK_CALENDAR (ID,DAY,ID_DAY_TYPE) values ('679',to_date('20.06.20','DD.MM.RR'),'1');
Insert into C##ANNA.WORK_CALENDAR (ID,DAY,ID_DAY_TYPE) values ('680',to_date('21.06.20','DD.MM.RR'),'1');
Insert into C##ANNA.WORK_CALENDAR (ID,DAY,ID_DAY_TYPE) values ('681',to_date('22.06.20','DD.MM.RR'),'2');
Insert into C##ANNA.WORK_CALENDAR (ID,DAY,ID_DAY_TYPE) values ('682',to_date('23.06.20','DD.MM.RR'),'2');
Insert into C##ANNA.WORK_CALENDAR (ID,DAY,ID_DAY_TYPE) values ('683',to_date('24.06.20','DD.MM.RR'),'2');
Insert into C##ANNA.WORK_CALENDAR (ID,DAY,ID_DAY_TYPE) values ('684',to_date('25.06.20','DD.MM.RR'),'2');
Insert into C##ANNA.WORK_CALENDAR (ID,DAY,ID_DAY_TYPE) values ('685',to_date('26.06.20','DD.MM.RR'),'2');
Insert into C##ANNA.WORK_CALENDAR (ID,DAY,ID_DAY_TYPE) values ('686',to_date('27.06.20','DD.MM.RR'),'1');
Insert into C##ANNA.WORK_CALENDAR (ID,DAY,ID_DAY_TYPE) values ('687',to_date('28.06.20','DD.MM.RR'),'1');
Insert into C##ANNA.WORK_CALENDAR (ID,DAY,ID_DAY_TYPE) values ('688',to_date('29.06.20','DD.MM.RR'),'2');
Insert into C##ANNA.WORK_CALENDAR (ID,DAY,ID_DAY_TYPE) values ('689',to_date('30.06.20','DD.MM.RR'),'2');
Insert into C##ANNA.WORK_CALENDAR (ID,DAY,ID_DAY_TYPE) values ('690',to_date('01.07.20','DD.MM.RR'),'2');
Insert into C##ANNA.WORK_CALENDAR (ID,DAY,ID_DAY_TYPE) values ('691',to_date('02.07.20','DD.MM.RR'),'2');
Insert into C##ANNA.WORK_CALENDAR (ID,DAY,ID_DAY_TYPE) values ('692',to_date('03.07.20','DD.MM.RR'),'2');
Insert into C##ANNA.WORK_CALENDAR (ID,DAY,ID_DAY_TYPE) values ('693',to_date('04.07.20','DD.MM.RR'),'1');
Insert into C##ANNA.WORK_CALENDAR (ID,DAY,ID_DAY_TYPE) values ('694',to_date('05.07.20','DD.MM.RR'),'1');
Insert into C##ANNA.WORK_CALENDAR (ID,DAY,ID_DAY_TYPE) values ('695',to_date('06.07.20','DD.MM.RR'),'2');
Insert into C##ANNA.WORK_CALENDAR (ID,DAY,ID_DAY_TYPE) values ('696',to_date('07.07.20','DD.MM.RR'),'2');
Insert into C##ANNA.WORK_CALENDAR (ID,DAY,ID_DAY_TYPE) values ('697',to_date('08.07.20','DD.MM.RR'),'2');
Insert into C##ANNA.WORK_CALENDAR (ID,DAY,ID_DAY_TYPE) values ('698',to_date('09.07.20','DD.MM.RR'),'2');
Insert into C##ANNA.WORK_CALENDAR (ID,DAY,ID_DAY_TYPE) values ('699',to_date('10.07.20','DD.MM.RR'),'2');
Insert into C##ANNA.WORK_CALENDAR (ID,DAY,ID_DAY_TYPE) values ('700',to_date('11.07.20','DD.MM.RR'),'1');
Insert into C##ANNA.WORK_CALENDAR (ID,DAY,ID_DAY_TYPE) values ('701',to_date('12.07.20','DD.MM.RR'),'1');
Insert into C##ANNA.WORK_CALENDAR (ID,DAY,ID_DAY_TYPE) values ('702',to_date('13.07.20','DD.MM.RR'),'2');
Insert into C##ANNA.WORK_CALENDAR (ID,DAY,ID_DAY_TYPE) values ('703',to_date('14.07.20','DD.MM.RR'),'2');
Insert into C##ANNA.WORK_CALENDAR (ID,DAY,ID_DAY_TYPE) values ('704',to_date('15.07.20','DD.MM.RR'),'2');
Insert into C##ANNA.WORK_CALENDAR (ID,DAY,ID_DAY_TYPE) values ('705',to_date('16.07.20','DD.MM.RR'),'2');
Insert into C##ANNA.WORK_CALENDAR (ID,DAY,ID_DAY_TYPE) values ('706',to_date('17.07.20','DD.MM.RR'),'2');
Insert into C##ANNA.WORK_CALENDAR (ID,DAY,ID_DAY_TYPE) values ('707',to_date('18.07.20','DD.MM.RR'),'1');
Insert into C##ANNA.WORK_CALENDAR (ID,DAY,ID_DAY_TYPE) values ('708',to_date('19.07.20','DD.MM.RR'),'1');
Insert into C##ANNA.WORK_CALENDAR (ID,DAY,ID_DAY_TYPE) values ('709',to_date('20.07.20','DD.MM.RR'),'2');
Insert into C##ANNA.WORK_CALENDAR (ID,DAY,ID_DAY_TYPE) values ('710',to_date('21.07.20','DD.MM.RR'),'2');
Insert into C##ANNA.WORK_CALENDAR (ID,DAY,ID_DAY_TYPE) values ('711',to_date('22.07.20','DD.MM.RR'),'2');
Insert into C##ANNA.WORK_CALENDAR (ID,DAY,ID_DAY_TYPE) values ('712',to_date('23.07.20','DD.MM.RR'),'2');
Insert into C##ANNA.WORK_CALENDAR (ID,DAY,ID_DAY_TYPE) values ('713',to_date('24.07.20','DD.MM.RR'),'2');
Insert into C##ANNA.WORK_CALENDAR (ID,DAY,ID_DAY_TYPE) values ('714',to_date('25.07.20','DD.MM.RR'),'1');
Insert into C##ANNA.WORK_CALENDAR (ID,DAY,ID_DAY_TYPE) values ('715',to_date('26.07.20','DD.MM.RR'),'1');
Insert into C##ANNA.WORK_CALENDAR (ID,DAY,ID_DAY_TYPE) values ('716',to_date('27.07.20','DD.MM.RR'),'2');
Insert into C##ANNA.WORK_CALENDAR (ID,DAY,ID_DAY_TYPE) values ('717',to_date('28.07.20','DD.MM.RR'),'2');
Insert into C##ANNA.WORK_CALENDAR (ID,DAY,ID_DAY_TYPE) values ('718',to_date('29.07.20','DD.MM.RR'),'2');
Insert into C##ANNA.WORK_CALENDAR (ID,DAY,ID_DAY_TYPE) values ('719',to_date('30.07.20','DD.MM.RR'),'2');
Insert into C##ANNA.WORK_CALENDAR (ID,DAY,ID_DAY_TYPE) values ('720',to_date('31.07.20','DD.MM.RR'),'2');
Insert into C##ANNA.WORK_CALENDAR (ID,DAY,ID_DAY_TYPE) values ('721',to_date('01.08.20','DD.MM.RR'),'1');
Insert into C##ANNA.WORK_CALENDAR (ID,DAY,ID_DAY_TYPE) values ('722',to_date('02.08.20','DD.MM.RR'),'1');
Insert into C##ANNA.WORK_CALENDAR (ID,DAY,ID_DAY_TYPE) values ('723',to_date('03.08.20','DD.MM.RR'),'2');
Insert into C##ANNA.WORK_CALENDAR (ID,DAY,ID_DAY_TYPE) values ('724',to_date('04.08.20','DD.MM.RR'),'2');
Insert into C##ANNA.WORK_CALENDAR (ID,DAY,ID_DAY_TYPE) values ('725',to_date('05.08.20','DD.MM.RR'),'2');
Insert into C##ANNA.WORK_CALENDAR (ID,DAY,ID_DAY_TYPE) values ('726',to_date('06.08.20','DD.MM.RR'),'2');
Insert into C##ANNA.WORK_CALENDAR (ID,DAY,ID_DAY_TYPE) values ('727',to_date('07.08.20','DD.MM.RR'),'2');
Insert into C##ANNA.WORK_CALENDAR (ID,DAY,ID_DAY_TYPE) values ('728',to_date('08.08.20','DD.MM.RR'),'1');
Insert into C##ANNA.WORK_CALENDAR (ID,DAY,ID_DAY_TYPE) values ('729',to_date('09.08.20','DD.MM.RR'),'1');
Insert into C##ANNA.WORK_CALENDAR (ID,DAY,ID_DAY_TYPE) values ('730',to_date('10.08.20','DD.MM.RR'),'2');
Insert into C##ANNA.WORK_CALENDAR (ID,DAY,ID_DAY_TYPE) values ('731',to_date('11.08.20','DD.MM.RR'),'2');
Insert into C##ANNA.WORK_CALENDAR (ID,DAY,ID_DAY_TYPE) values ('732',to_date('12.08.20','DD.MM.RR'),'2');
Insert into C##ANNA.WORK_CALENDAR (ID,DAY,ID_DAY_TYPE) values ('733',to_date('13.08.20','DD.MM.RR'),'2');
Insert into C##ANNA.WORK_CALENDAR (ID,DAY,ID_DAY_TYPE) values ('734',to_date('14.08.20','DD.MM.RR'),'2');
Insert into C##ANNA.WORK_CALENDAR (ID,DAY,ID_DAY_TYPE) values ('735',to_date('15.08.20','DD.MM.RR'),'1');
Insert into C##ANNA.WORK_CALENDAR (ID,DAY,ID_DAY_TYPE) values ('736',to_date('16.08.20','DD.MM.RR'),'1');
Insert into C##ANNA.WORK_CALENDAR (ID,DAY,ID_DAY_TYPE) values ('737',to_date('17.08.20','DD.MM.RR'),'2');
Insert into C##ANNA.WORK_CALENDAR (ID,DAY,ID_DAY_TYPE) values ('738',to_date('18.08.20','DD.MM.RR'),'2');
Insert into C##ANNA.WORK_CALENDAR (ID,DAY,ID_DAY_TYPE) values ('739',to_date('19.08.20','DD.MM.RR'),'2');
Insert into C##ANNA.WORK_CALENDAR (ID,DAY,ID_DAY_TYPE) values ('740',to_date('20.08.20','DD.MM.RR'),'2');
Insert into C##ANNA.WORK_CALENDAR (ID,DAY,ID_DAY_TYPE) values ('741',to_date('21.08.20','DD.MM.RR'),'2');
Insert into C##ANNA.WORK_CALENDAR (ID,DAY,ID_DAY_TYPE) values ('742',to_date('22.08.20','DD.MM.RR'),'1');
Insert into C##ANNA.WORK_CALENDAR (ID,DAY,ID_DAY_TYPE) values ('743',to_date('23.08.20','DD.MM.RR'),'1');
Insert into C##ANNA.WORK_CALENDAR (ID,DAY,ID_DAY_TYPE) values ('744',to_date('24.08.20','DD.MM.RR'),'2');
Insert into C##ANNA.WORK_CALENDAR (ID,DAY,ID_DAY_TYPE) values ('745',to_date('25.08.20','DD.MM.RR'),'2');
Insert into C##ANNA.WORK_CALENDAR (ID,DAY,ID_DAY_TYPE) values ('746',to_date('26.08.20','DD.MM.RR'),'2');
Insert into C##ANNA.WORK_CALENDAR (ID,DAY,ID_DAY_TYPE) values ('747',to_date('27.08.20','DD.MM.RR'),'2');
Insert into C##ANNA.WORK_CALENDAR (ID,DAY,ID_DAY_TYPE) values ('748',to_date('28.08.20','DD.MM.RR'),'2');
Insert into C##ANNA.WORK_CALENDAR (ID,DAY,ID_DAY_TYPE) values ('749',to_date('29.08.20','DD.MM.RR'),'1');
Insert into C##ANNA.WORK_CALENDAR (ID,DAY,ID_DAY_TYPE) values ('750',to_date('30.08.20','DD.MM.RR'),'1');
Insert into C##ANNA.WORK_CALENDAR (ID,DAY,ID_DAY_TYPE) values ('751',to_date('31.08.20','DD.MM.RR'),'2');
Insert into C##ANNA.WORK_CALENDAR (ID,DAY,ID_DAY_TYPE) values ('752',to_date('01.09.20','DD.MM.RR'),'2');
Insert into C##ANNA.WORK_CALENDAR (ID,DAY,ID_DAY_TYPE) values ('753',to_date('02.09.20','DD.MM.RR'),'2');
Insert into C##ANNA.WORK_CALENDAR (ID,DAY,ID_DAY_TYPE) values ('754',to_date('03.09.20','DD.MM.RR'),'2');
Insert into C##ANNA.WORK_CALENDAR (ID,DAY,ID_DAY_TYPE) values ('755',to_date('04.09.20','DD.MM.RR'),'2');
Insert into C##ANNA.WORK_CALENDAR (ID,DAY,ID_DAY_TYPE) values ('756',to_date('05.09.20','DD.MM.RR'),'1');
Insert into C##ANNA.WORK_CALENDAR (ID,DAY,ID_DAY_TYPE) values ('757',to_date('06.09.20','DD.MM.RR'),'1');
Insert into C##ANNA.WORK_CALENDAR (ID,DAY,ID_DAY_TYPE) values ('758',to_date('07.09.20','DD.MM.RR'),'2');
Insert into C##ANNA.WORK_CALENDAR (ID,DAY,ID_DAY_TYPE) values ('759',to_date('08.09.20','DD.MM.RR'),'2');
Insert into C##ANNA.WORK_CALENDAR (ID,DAY,ID_DAY_TYPE) values ('760',to_date('09.09.20','DD.MM.RR'),'2');
Insert into C##ANNA.WORK_CALENDAR (ID,DAY,ID_DAY_TYPE) values ('761',to_date('10.09.20','DD.MM.RR'),'2');
Insert into C##ANNA.WORK_CALENDAR (ID,DAY,ID_DAY_TYPE) values ('762',to_date('11.09.20','DD.MM.RR'),'2');
Insert into C##ANNA.WORK_CALENDAR (ID,DAY,ID_DAY_TYPE) values ('763',to_date('12.09.20','DD.MM.RR'),'1');
Insert into C##ANNA.WORK_CALENDAR (ID,DAY,ID_DAY_TYPE) values ('764',to_date('13.09.20','DD.MM.RR'),'1');
Insert into C##ANNA.WORK_CALENDAR (ID,DAY,ID_DAY_TYPE) values ('765',to_date('14.09.20','DD.MM.RR'),'2');
Insert into C##ANNA.WORK_CALENDAR (ID,DAY,ID_DAY_TYPE) values ('766',to_date('15.09.20','DD.MM.RR'),'2');
Insert into C##ANNA.WORK_CALENDAR (ID,DAY,ID_DAY_TYPE) values ('767',to_date('16.09.20','DD.MM.RR'),'2');
Insert into C##ANNA.WORK_CALENDAR (ID,DAY,ID_DAY_TYPE) values ('768',to_date('17.09.20','DD.MM.RR'),'2');
Insert into C##ANNA.WORK_CALENDAR (ID,DAY,ID_DAY_TYPE) values ('769',to_date('18.09.20','DD.MM.RR'),'2');
Insert into C##ANNA.WORK_CALENDAR (ID,DAY,ID_DAY_TYPE) values ('770',to_date('19.09.20','DD.MM.RR'),'1');
Insert into C##ANNA.WORK_CALENDAR (ID,DAY,ID_DAY_TYPE) values ('771',to_date('20.09.20','DD.MM.RR'),'1');
Insert into C##ANNA.WORK_CALENDAR (ID,DAY,ID_DAY_TYPE) values ('772',to_date('21.09.20','DD.MM.RR'),'2');
Insert into C##ANNA.WORK_CALENDAR (ID,DAY,ID_DAY_TYPE) values ('773',to_date('22.09.20','DD.MM.RR'),'2');
Insert into C##ANNA.WORK_CALENDAR (ID,DAY,ID_DAY_TYPE) values ('774',to_date('23.09.20','DD.MM.RR'),'2');
Insert into C##ANNA.WORK_CALENDAR (ID,DAY,ID_DAY_TYPE) values ('775',to_date('24.09.20','DD.MM.RR'),'2');
Insert into C##ANNA.WORK_CALENDAR (ID,DAY,ID_DAY_TYPE) values ('776',to_date('25.09.20','DD.MM.RR'),'2');
Insert into C##ANNA.WORK_CALENDAR (ID,DAY,ID_DAY_TYPE) values ('777',to_date('26.09.20','DD.MM.RR'),'1');
Insert into C##ANNA.WORK_CALENDAR (ID,DAY,ID_DAY_TYPE) values ('778',to_date('27.09.20','DD.MM.RR'),'1');
Insert into C##ANNA.WORK_CALENDAR (ID,DAY,ID_DAY_TYPE) values ('779',to_date('28.09.20','DD.MM.RR'),'2');
Insert into C##ANNA.WORK_CALENDAR (ID,DAY,ID_DAY_TYPE) values ('780',to_date('29.09.20','DD.MM.RR'),'2');
Insert into C##ANNA.WORK_CALENDAR (ID,DAY,ID_DAY_TYPE) values ('781',to_date('30.09.20','DD.MM.RR'),'2');
Insert into C##ANNA.WORK_CALENDAR (ID,DAY,ID_DAY_TYPE) values ('782',to_date('01.10.20','DD.MM.RR'),'2');
Insert into C##ANNA.WORK_CALENDAR (ID,DAY,ID_DAY_TYPE) values ('783',to_date('02.10.20','DD.MM.RR'),'2');
Insert into C##ANNA.WORK_CALENDAR (ID,DAY,ID_DAY_TYPE) values ('784',to_date('03.10.20','DD.MM.RR'),'1');
Insert into C##ANNA.WORK_CALENDAR (ID,DAY,ID_DAY_TYPE) values ('785',to_date('04.10.20','DD.MM.RR'),'1');
Insert into C##ANNA.WORK_CALENDAR (ID,DAY,ID_DAY_TYPE) values ('786',to_date('05.10.20','DD.MM.RR'),'2');
Insert into C##ANNA.WORK_CALENDAR (ID,DAY,ID_DAY_TYPE) values ('787',to_date('06.10.20','DD.MM.RR'),'2');
Insert into C##ANNA.WORK_CALENDAR (ID,DAY,ID_DAY_TYPE) values ('788',to_date('07.10.20','DD.MM.RR'),'2');
Insert into C##ANNA.WORK_CALENDAR (ID,DAY,ID_DAY_TYPE) values ('789',to_date('08.10.20','DD.MM.RR'),'2');
Insert into C##ANNA.WORK_CALENDAR (ID,DAY,ID_DAY_TYPE) values ('790',to_date('09.10.20','DD.MM.RR'),'2');
Insert into C##ANNA.WORK_CALENDAR (ID,DAY,ID_DAY_TYPE) values ('791',to_date('10.10.20','DD.MM.RR'),'1');
Insert into C##ANNA.WORK_CALENDAR (ID,DAY,ID_DAY_TYPE) values ('792',to_date('11.10.20','DD.MM.RR'),'1');
Insert into C##ANNA.WORK_CALENDAR (ID,DAY,ID_DAY_TYPE) values ('793',to_date('12.10.20','DD.MM.RR'),'2');
Insert into C##ANNA.WORK_CALENDAR (ID,DAY,ID_DAY_TYPE) values ('794',to_date('13.10.20','DD.MM.RR'),'2');
Insert into C##ANNA.WORK_CALENDAR (ID,DAY,ID_DAY_TYPE) values ('795',to_date('14.10.20','DD.MM.RR'),'2');
Insert into C##ANNA.WORK_CALENDAR (ID,DAY,ID_DAY_TYPE) values ('796',to_date('15.10.20','DD.MM.RR'),'2');
Insert into C##ANNA.WORK_CALENDAR (ID,DAY,ID_DAY_TYPE) values ('797',to_date('16.10.20','DD.MM.RR'),'2');
Insert into C##ANNA.WORK_CALENDAR (ID,DAY,ID_DAY_TYPE) values ('798',to_date('17.10.20','DD.MM.RR'),'1');
Insert into C##ANNA.WORK_CALENDAR (ID,DAY,ID_DAY_TYPE) values ('799',to_date('18.10.20','DD.MM.RR'),'1');
Insert into C##ANNA.WORK_CALENDAR (ID,DAY,ID_DAY_TYPE) values ('800',to_date('19.10.20','DD.MM.RR'),'2');
Insert into C##ANNA.WORK_CALENDAR (ID,DAY,ID_DAY_TYPE) values ('801',to_date('20.10.20','DD.MM.RR'),'2');
Insert into C##ANNA.WORK_CALENDAR (ID,DAY,ID_DAY_TYPE) values ('802',to_date('21.10.20','DD.MM.RR'),'2');
Insert into C##ANNA.WORK_CALENDAR (ID,DAY,ID_DAY_TYPE) values ('803',to_date('22.10.20','DD.MM.RR'),'2');
Insert into C##ANNA.WORK_CALENDAR (ID,DAY,ID_DAY_TYPE) values ('804',to_date('23.10.20','DD.MM.RR'),'2');
Insert into C##ANNA.WORK_CALENDAR (ID,DAY,ID_DAY_TYPE) values ('805',to_date('24.10.20','DD.MM.RR'),'1');
Insert into C##ANNA.WORK_CALENDAR (ID,DAY,ID_DAY_TYPE) values ('806',to_date('25.10.20','DD.MM.RR'),'1');
Insert into C##ANNA.WORK_CALENDAR (ID,DAY,ID_DAY_TYPE) values ('807',to_date('26.10.20','DD.MM.RR'),'2');
Insert into C##ANNA.WORK_CALENDAR (ID,DAY,ID_DAY_TYPE) values ('808',to_date('27.10.20','DD.MM.RR'),'2');
Insert into C##ANNA.WORK_CALENDAR (ID,DAY,ID_DAY_TYPE) values ('809',to_date('28.10.20','DD.MM.RR'),'2');
Insert into C##ANNA.WORK_CALENDAR (ID,DAY,ID_DAY_TYPE) values ('810',to_date('29.10.20','DD.MM.RR'),'2');
Insert into C##ANNA.WORK_CALENDAR (ID,DAY,ID_DAY_TYPE) values ('811',to_date('30.10.20','DD.MM.RR'),'2');
Insert into C##ANNA.WORK_CALENDAR (ID,DAY,ID_DAY_TYPE) values ('812',to_date('31.10.20','DD.MM.RR'),'1');
Insert into C##ANNA.WORK_CALENDAR (ID,DAY,ID_DAY_TYPE) values ('813',to_date('01.11.20','DD.MM.RR'),'1');
Insert into C##ANNA.WORK_CALENDAR (ID,DAY,ID_DAY_TYPE) values ('814',to_date('02.11.20','DD.MM.RR'),'2');
Insert into C##ANNA.WORK_CALENDAR (ID,DAY,ID_DAY_TYPE) values ('815',to_date('03.11.20','DD.MM.RR'),'3');
Insert into C##ANNA.WORK_CALENDAR (ID,DAY,ID_DAY_TYPE) values ('816',to_date('04.11.20','DD.MM.RR'),'2');
Insert into C##ANNA.WORK_CALENDAR (ID,DAY,ID_DAY_TYPE) values ('817',to_date('05.11.20','DD.MM.RR'),'2');
Insert into C##ANNA.WORK_CALENDAR (ID,DAY,ID_DAY_TYPE) values ('818',to_date('06.11.20','DD.MM.RR'),'2');
Insert into C##ANNA.WORK_CALENDAR (ID,DAY,ID_DAY_TYPE) values ('819',to_date('07.11.20','DD.MM.RR'),'1');
Insert into C##ANNA.WORK_CALENDAR (ID,DAY,ID_DAY_TYPE) values ('820',to_date('08.11.20','DD.MM.RR'),'1');
Insert into C##ANNA.WORK_CALENDAR (ID,DAY,ID_DAY_TYPE) values ('821',to_date('09.11.20','DD.MM.RR'),'2');
Insert into C##ANNA.WORK_CALENDAR (ID,DAY,ID_DAY_TYPE) values ('822',to_date('10.11.20','DD.MM.RR'),'2');
Insert into C##ANNA.WORK_CALENDAR (ID,DAY,ID_DAY_TYPE) values ('823',to_date('11.11.20','DD.MM.RR'),'2');
Insert into C##ANNA.WORK_CALENDAR (ID,DAY,ID_DAY_TYPE) values ('824',to_date('12.11.20','DD.MM.RR'),'2');
Insert into C##ANNA.WORK_CALENDAR (ID,DAY,ID_DAY_TYPE) values ('825',to_date('13.11.20','DD.MM.RR'),'2');
Insert into C##ANNA.WORK_CALENDAR (ID,DAY,ID_DAY_TYPE) values ('826',to_date('14.11.20','DD.MM.RR'),'1');
Insert into C##ANNA.WORK_CALENDAR (ID,DAY,ID_DAY_TYPE) values ('827',to_date('15.11.20','DD.MM.RR'),'1');
Insert into C##ANNA.WORK_CALENDAR (ID,DAY,ID_DAY_TYPE) values ('828',to_date('16.11.20','DD.MM.RR'),'2');
Insert into C##ANNA.WORK_CALENDAR (ID,DAY,ID_DAY_TYPE) values ('829',to_date('17.11.20','DD.MM.RR'),'2');
Insert into C##ANNA.WORK_CALENDAR (ID,DAY,ID_DAY_TYPE) values ('830',to_date('18.11.20','DD.MM.RR'),'2');
Insert into C##ANNA.WORK_CALENDAR (ID,DAY,ID_DAY_TYPE) values ('831',to_date('19.11.20','DD.MM.RR'),'2');
Insert into C##ANNA.WORK_CALENDAR (ID,DAY,ID_DAY_TYPE) values ('832',to_date('20.11.20','DD.MM.RR'),'2');
Insert into C##ANNA.WORK_CALENDAR (ID,DAY,ID_DAY_TYPE) values ('833',to_date('21.11.20','DD.MM.RR'),'1');
Insert into C##ANNA.WORK_CALENDAR (ID,DAY,ID_DAY_TYPE) values ('834',to_date('22.11.20','DD.MM.RR'),'1');
Insert into C##ANNA.WORK_CALENDAR (ID,DAY,ID_DAY_TYPE) values ('835',to_date('23.11.20','DD.MM.RR'),'2');
Insert into C##ANNA.WORK_CALENDAR (ID,DAY,ID_DAY_TYPE) values ('836',to_date('24.11.20','DD.MM.RR'),'2');
Insert into C##ANNA.WORK_CALENDAR (ID,DAY,ID_DAY_TYPE) values ('837',to_date('25.11.20','DD.MM.RR'),'2');
Insert into C##ANNA.WORK_CALENDAR (ID,DAY,ID_DAY_TYPE) values ('838',to_date('26.11.20','DD.MM.RR'),'2');
Insert into C##ANNA.WORK_CALENDAR (ID,DAY,ID_DAY_TYPE) values ('839',to_date('27.11.20','DD.MM.RR'),'2');
Insert into C##ANNA.WORK_CALENDAR (ID,DAY,ID_DAY_TYPE) values ('840',to_date('28.11.20','DD.MM.RR'),'1');
Insert into C##ANNA.WORK_CALENDAR (ID,DAY,ID_DAY_TYPE) values ('841',to_date('29.11.20','DD.MM.RR'),'1');
Insert into C##ANNA.WORK_CALENDAR (ID,DAY,ID_DAY_TYPE) values ('842',to_date('30.11.20','DD.MM.RR'),'2');
Insert into C##ANNA.WORK_CALENDAR (ID,DAY,ID_DAY_TYPE) values ('843',to_date('01.12.20','DD.MM.RR'),'2');
Insert into C##ANNA.WORK_CALENDAR (ID,DAY,ID_DAY_TYPE) values ('844',to_date('02.12.20','DD.MM.RR'),'2');
Insert into C##ANNA.WORK_CALENDAR (ID,DAY,ID_DAY_TYPE) values ('845',to_date('03.12.20','DD.MM.RR'),'2');
Insert into C##ANNA.WORK_CALENDAR (ID,DAY,ID_DAY_TYPE) values ('846',to_date('04.12.20','DD.MM.RR'),'2');
Insert into C##ANNA.WORK_CALENDAR (ID,DAY,ID_DAY_TYPE) values ('847',to_date('05.12.20','DD.MM.RR'),'1');
Insert into C##ANNA.WORK_CALENDAR (ID,DAY,ID_DAY_TYPE) values ('848',to_date('06.12.20','DD.MM.RR'),'1');
Insert into C##ANNA.WORK_CALENDAR (ID,DAY,ID_DAY_TYPE) values ('849',to_date('07.12.20','DD.MM.RR'),'2');
Insert into C##ANNA.WORK_CALENDAR (ID,DAY,ID_DAY_TYPE) values ('850',to_date('08.12.20','DD.MM.RR'),'2');
Insert into C##ANNA.WORK_CALENDAR (ID,DAY,ID_DAY_TYPE) values ('851',to_date('09.12.20','DD.MM.RR'),'2');
Insert into C##ANNA.WORK_CALENDAR (ID,DAY,ID_DAY_TYPE) values ('852',to_date('10.12.20','DD.MM.RR'),'2');
Insert into C##ANNA.WORK_CALENDAR (ID,DAY,ID_DAY_TYPE) values ('853',to_date('11.12.20','DD.MM.RR'),'2');
Insert into C##ANNA.WORK_CALENDAR (ID,DAY,ID_DAY_TYPE) values ('854',to_date('12.12.20','DD.MM.RR'),'1');
Insert into C##ANNA.WORK_CALENDAR (ID,DAY,ID_DAY_TYPE) values ('855',to_date('13.12.20','DD.MM.RR'),'1');
Insert into C##ANNA.WORK_CALENDAR (ID,DAY,ID_DAY_TYPE) values ('856',to_date('14.12.20','DD.MM.RR'),'2');
Insert into C##ANNA.WORK_CALENDAR (ID,DAY,ID_DAY_TYPE) values ('857',to_date('15.12.20','DD.MM.RR'),'2');
Insert into C##ANNA.WORK_CALENDAR (ID,DAY,ID_DAY_TYPE) values ('858',to_date('16.12.20','DD.MM.RR'),'2');
Insert into C##ANNA.WORK_CALENDAR (ID,DAY,ID_DAY_TYPE) values ('859',to_date('17.12.20','DD.MM.RR'),'2');
Insert into C##ANNA.WORK_CALENDAR (ID,DAY,ID_DAY_TYPE) values ('860',to_date('18.12.20','DD.MM.RR'),'2');
Insert into C##ANNA.WORK_CALENDAR (ID,DAY,ID_DAY_TYPE) values ('861',to_date('19.12.20','DD.MM.RR'),'1');
Insert into C##ANNA.WORK_CALENDAR (ID,DAY,ID_DAY_TYPE) values ('862',to_date('20.12.20','DD.MM.RR'),'1');
Insert into C##ANNA.WORK_CALENDAR (ID,DAY,ID_DAY_TYPE) values ('863',to_date('21.12.20','DD.MM.RR'),'2');
Insert into C##ANNA.WORK_CALENDAR (ID,DAY,ID_DAY_TYPE) values ('864',to_date('22.12.20','DD.MM.RR'),'2');
Insert into C##ANNA.WORK_CALENDAR (ID,DAY,ID_DAY_TYPE) values ('865',to_date('23.12.20','DD.MM.RR'),'2');
Insert into C##ANNA.WORK_CALENDAR (ID,DAY,ID_DAY_TYPE) values ('866',to_date('24.12.20','DD.MM.RR'),'2');
Insert into C##ANNA.WORK_CALENDAR (ID,DAY,ID_DAY_TYPE) values ('867',to_date('25.12.20','DD.MM.RR'),'2');
Insert into C##ANNA.WORK_CALENDAR (ID,DAY,ID_DAY_TYPE) values ('868',to_date('26.12.20','DD.MM.RR'),'1');
Insert into C##ANNA.WORK_CALENDAR (ID,DAY,ID_DAY_TYPE) values ('869',to_date('27.12.20','DD.MM.RR'),'1');
Insert into C##ANNA.WORK_CALENDAR (ID,DAY,ID_DAY_TYPE) values ('870',to_date('28.12.20','DD.MM.RR'),'2');
Insert into C##ANNA.WORK_CALENDAR (ID,DAY,ID_DAY_TYPE) values ('871',to_date('29.12.20','DD.MM.RR'),'2');
Insert into C##ANNA.WORK_CALENDAR (ID,DAY,ID_DAY_TYPE) values ('872',to_date('30.12.20','DD.MM.RR'),'2');
Insert into C##ANNA.WORK_CALENDAR (ID,DAY,ID_DAY_TYPE) values ('873',to_date('31.12.20','DD.MM.RR'),'4');
--------------------------------------------------------
--  DDL for Index CALENDAR_DAY_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##ANNA"."CALENDAR_DAY_PK" ON "C##ANNA"."DAY_TYPES" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index DEPARTMENTS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##ANNA"."DEPARTMENTS_PK" ON "C##ANNA"."DEPARTMENTS" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index EMPLOYEES_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##ANNA"."EMPLOYEES_PK" ON "C##ANNA"."EMPLOYEES" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index ID_DAY_TYPE
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##ANNA"."ID_DAY_TYPE" ON "C##ANNA"."WORK_CALENDAR" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index MARKS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##ANNA"."MARKS_PK" ON "C##ANNA"."MARKS" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index ROLES_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##ANNA"."ROLES_PK" ON "C##ANNA"."ROLES" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index USERS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##ANNA"."USERS_PK" ON "C##ANNA"."USERS" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Procedure COUNT_OF_WORKDAYS
--------------------------------------------------------
set define off;

  CREATE OR REPLACE EDITIONABLE PROCEDURE "C##ANNA"."COUNT_OF_WORKDAYS" (month_name IN varchar2, emp_id IN NUMBER, count_workDays OUT Number )
as
begin
    select count(*) into count_workDays
    from employees_and_calendar_days
    inner join work_calendar on employees_and_calendar_days.work_calendar_id = work_calendar.id
    where mark_id = 1
        and employees_and_calendar_days.employee_id = emp_id
        and to_char(work_calendar.day, 'Month YYYY') = month_name;
end;

/
--------------------------------------------------------
--  DDL for Procedure WORKDAYS_IN_MONTH
--------------------------------------------------------
set define off;

  CREATE OR REPLACE EDITIONABLE PROCEDURE "C##ANNA"."WORKDAYS_IN_MONTH" (month_name IN varchar2, emp_id IN NUMBER, tmp OUT sys_refcursor)
as
begin
    open tmp for
        select work_calendar.id, to_char(work_calendar.day, 'dd'), day_types.title, marks.id, marks.title, marks.transcription
            from work_calendar
            left outer join (
                select * from employees_and_calendar_days
                where employees_and_calendar_days.employee_id = emp_id
            ) T
            on work_calendar.id = T.work_calendar_id
            left outer join day_types on work_calendar.id_day_type = day_types.id
            left outer join marks on T.mark_id = marks.id
            where to_char(work_calendar.day, 'Month YYYY') = month_name
            order by work_calendar.day;
end;

/
--------------------------------------------------------
--  DDL for Package USER_SECURITY
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE PACKAGE "C##ANNA"."USER_SECURITY" as

  function get_hash (p_username  IN  VARCHAR2,
                     p_password  IN  VARCHAR2)
    return VARCHAR2;

  procedure add_user (p_username  IN  VARCHAR2,
                      p_password  IN  VARCHAR2,
                      p_acc_type_id   IN  NUMBER,
                      p_id        OUT NUMBER);

  PROCEDURE valid_user (p_username  IN  VARCHAR2,
                        p_password  IN  VARCHAR2,
                        p_id       OUT NUMBER);

END;

/
--------------------------------------------------------
--  DDL for Package Body USER_SECURITY
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE PACKAGE BODY "C##ANNA"."USER_SECURITY" AS

  function get_hash (p_username  IN  VARCHAR2,
                     p_password  IN  VARCHAR2)
    return VARCHAR2 as
    l_salt VARCHAR2(30) := 'SomeRandomSalt';
  begin
    return DBMS_CRYPTO.hash(UTL_RAW.CAST_TO_RAW(p_username || l_salt || p_password), DBMS_CRYPTO.HASH_SH1);
  end;

  procedure add_user (p_username  IN  VARCHAR2,
                      p_password  IN  VARCHAR2,
                      p_acc_type_id   IN  NUMBER,
                      p_id        OUT NUMBER) as
  begin
    insert into users (
      login,
      password,
      id_role
    )
    values (
      p_username,
      get_hash(p_username, p_password),
      p_acc_type_id
    )
    returning id into p_id;

    COMMIT;
  END;

  PROCEDURE valid_user (p_username  IN  VARCHAR2,
                        p_password  IN  VARCHAR2,
                        p_id       OUT NUMBER) AS
  BEGIN
    SELECT id
    INTO   p_id
    FROM   users
    WHERE  login = p_username
    AND    password = get_hash(p_username, p_password);
  EXCEPTION
    WHEN NO_DATA_FOUND THEN
      RAISE_APPLICATION_ERROR(-20007, 'Invalid username/password.');
  END;

END;

/
--------------------------------------------------------
--  Constraints for Table EMPLOYEES_AND_CALENDAR_DAYS
--------------------------------------------------------

  ALTER TABLE "C##ANNA"."EMPLOYEES_AND_CALENDAR_DAYS" ADD UNIQUE ("EMPLOYEE_ID", "MARK_ID", "WORK_CALENDAR_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table MARKS
--------------------------------------------------------

  ALTER TABLE "C##ANNA"."MARKS" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "C##ANNA"."MARKS" MODIFY ("TITLE" NOT NULL ENABLE);
  ALTER TABLE "C##ANNA"."MARKS" MODIFY ("TRANSCRIPTION" NOT NULL ENABLE);
  ALTER TABLE "C##ANNA"."MARKS" ADD CONSTRAINT "MARKS_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table DEPARTMENTS
--------------------------------------------------------

  ALTER TABLE "C##ANNA"."DEPARTMENTS" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "C##ANNA"."DEPARTMENTS" MODIFY ("NAME" NOT NULL ENABLE);
  ALTER TABLE "C##ANNA"."DEPARTMENTS" ADD CONSTRAINT "DEPARTMENTS_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table ROLES
--------------------------------------------------------

  ALTER TABLE "C##ANNA"."ROLES" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "C##ANNA"."ROLES" MODIFY ("NAME" NOT NULL ENABLE);
  ALTER TABLE "C##ANNA"."ROLES" ADD CONSTRAINT "ROLES_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table EMPLOYEES
--------------------------------------------------------

  ALTER TABLE "C##ANNA"."EMPLOYEES" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "C##ANNA"."EMPLOYEES" MODIFY ("NAME" NOT NULL ENABLE);
  ALTER TABLE "C##ANNA"."EMPLOYEES" MODIFY ("SURNAME" NOT NULL ENABLE);
  ALTER TABLE "C##ANNA"."EMPLOYEES" MODIFY ("DATE_OF_BIRTHDAY" NOT NULL ENABLE);
  ALTER TABLE "C##ANNA"."EMPLOYEES" MODIFY ("ID_DEPARTMENT" NOT NULL ENABLE);
  ALTER TABLE "C##ANNA"."EMPLOYEES" MODIFY ("POSITION" NOT NULL ENABLE);
  ALTER TABLE "C##ANNA"."EMPLOYEES" MODIFY ("ADDRESS" NOT NULL ENABLE);
  ALTER TABLE "C##ANNA"."EMPLOYEES" ADD CONSTRAINT "EMPLOYEES_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table USERS
--------------------------------------------------------

  ALTER TABLE "C##ANNA"."USERS" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "C##ANNA"."USERS" MODIFY ("LOGIN" NOT NULL ENABLE);
  ALTER TABLE "C##ANNA"."USERS" MODIFY ("PASSWORD" NOT NULL ENABLE);
  ALTER TABLE "C##ANNA"."USERS" MODIFY ("ID_ROLE" NOT NULL ENABLE);
  ALTER TABLE "C##ANNA"."USERS" ADD CONSTRAINT "USERS_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table WORK_CALENDAR
--------------------------------------------------------

  ALTER TABLE "C##ANNA"."WORK_CALENDAR" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "C##ANNA"."WORK_CALENDAR" MODIFY ("DAY" NOT NULL ENABLE);
  ALTER TABLE "C##ANNA"."WORK_CALENDAR" MODIFY ("ID_DAY_TYPE" NOT NULL ENABLE);
  ALTER TABLE "C##ANNA"."WORK_CALENDAR" ADD CONSTRAINT "ID_DAY_TYPE" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table DAY_TYPES
--------------------------------------------------------

  ALTER TABLE "C##ANNA"."DAY_TYPES" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "C##ANNA"."DAY_TYPES" MODIFY ("TITLE" NOT NULL ENABLE);
  ALTER TABLE "C##ANNA"."DAY_TYPES" ADD CONSTRAINT "CALENDAR_DAY_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table EMPLOYEES
--------------------------------------------------------

  ALTER TABLE "C##ANNA"."EMPLOYEES" ADD FOREIGN KEY ("ID_DEPARTMENT")
	  REFERENCES "C##ANNA"."DEPARTMENTS" ("ID") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table EMPLOYEES_AND_CALENDAR_DAYS
--------------------------------------------------------

  ALTER TABLE "C##ANNA"."EMPLOYEES_AND_CALENDAR_DAYS" ADD FOREIGN KEY ("EMPLOYEE_ID")
	  REFERENCES "C##ANNA"."EMPLOYEES" ("ID") ENABLE;
  ALTER TABLE "C##ANNA"."EMPLOYEES_AND_CALENDAR_DAYS" ADD FOREIGN KEY ("MARK_ID")
	  REFERENCES "C##ANNA"."MARKS" ("ID") ENABLE;
  ALTER TABLE "C##ANNA"."EMPLOYEES_AND_CALENDAR_DAYS" ADD FOREIGN KEY ("WORK_CALENDAR_ID")
	  REFERENCES "C##ANNA"."WORK_CALENDAR" ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table USERS
--------------------------------------------------------

  ALTER TABLE "C##ANNA"."USERS" ADD FOREIGN KEY ("ID_ROLE")
	  REFERENCES "C##ANNA"."ROLES" ("ID") ON DELETE CASCADE ENABLE;
